/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "xqfdwbmkuwoyqhnqhryv"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxZmR3Ym1rdXdveXFobnFocnl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUyMzkzMTUsImV4cCI6MjA5MDgxNTMxNX0.pbgHyTzlKz2PApOc-KhdjpLkmVX7gFyG_ctA2-x_-Gc"